# Add configuration values here, as shown below.
#
# pusher_app_id: "2954"
# pusher_key: 7381a978f7dd7f9a1117
# pusher_secret: abdc3b896a0ffb85d373
# stripe_api_key: sk_test_2J0l093xOyW72XUYJHE4Dv2r
# stripe_publishable_key: pk_test_ro9jV5SNwGb1yYlQfzG17LHK
#
# production:
#   stripe_api_key: sk_live_EeHnL644i6zo4Iyq4v1KdV9H
#   stripe_publishable_key: pk_live_9lcthxpSIHbGwmdO941O1XVU
REDSYSURL: "https://sis-t.redsys.es:25443/sis/rest/trataPeticionREST"
MERCHANTCODE: "352263560"
MERCHANTTERMINAL: "1"
MERCHANTCURRENCY: "978"
MERCHANTSIGNATURE: "sq7HjrUOBfKmC576ILgskD5srU870gJ7"
HOST_NAME: "distropayment.com"
EMAIL_USERNAME: "apikey"
EMAIL_PASSWORD: "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"
NEUTRINO_API: "https://neutrinoapi.net/bin-lookup"
CARD_BIN_USER: "yawarsultan"
CARD_BIN_LIST_KEY: "cDvIX4gWwznAjRB30bM365KFPqt5g8poU0aSVNBSO0ugoGdu"
STRIPE_SECRET: "sk_test_kDSa9QcGWN0O1HWn6pgNJ5fp00eNEv2lhh"
